<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260212113958 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agent_statuses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agent_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7D2107853414710B ON agent_statuses (agent_id)');
        $this->addSql('CREATE TABLE call_qualifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, qualified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, call_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E1AA67F50A89B2C ON call_qualifications (call_id)');
        $this->addSql('CREATE TABLE calls (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duration INT DEFAULT NULL, status VARCHAR(50) NOT NULL, recording_path VARCHAR(255) DEFAULT NULL, campaign_id INT NOT NULL, agent_id INT NOT NULL, contact_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DAA35C8FF639F774 ON calls (campaign_id)');
        $this->addSql('CREATE INDEX IDX_DAA35C8F3414710B ON calls (agent_id)');
        $this->addSql('CREATE INDEX IDX_DAA35C8FE7A1254A ON calls (contact_id)');
        $this->addSql('CREATE TABLE campaign_fields (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, field_type VARCHAR(50) NOT NULL, options JSON DEFAULT NULL, is_required BOOLEAN DEFAULT false NOT NULL, position INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, campaign_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A3A69A25F639F774 ON campaign_fields (campaign_id)');
        $this->addSql('CREATE TABLE campaign_users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role_in_campaign VARCHAR(50) DEFAULT NULL, assigned_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, campaign_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5A86C186F639F774 ON campaign_users (campaign_id)');
        $this->addSql('CREATE INDEX IDX_5A86C186A76ED395 ON campaign_users (user_id)');
        $this->addSql('CREATE TABLE campaigns (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, responsable_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E373747053C59D72 ON campaigns (responsable_id)');
        $this->addSql('CREATE TABLE contacts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, telephone VARCHAR(20) NOT NULL, email VARCHAR(100) DEFAULT NULL, source VARCHAR(100) DEFAULT NULL, autre JSON DEFAULT NULL, status VARCHAR(50) DEFAULT \'nouveau\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, campaign_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_33401573F639F774 ON contacts (campaign_id)');
        $this->addSql('CREATE TABLE qualification_fields (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, required BOOLEAN NOT NULL, campaign_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_94E34B05F639F774 ON qualification_fields (campaign_id)');
        $this->addSql('CREATE TABLE qualification_values (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value TEXT NOT NULL, call_id INT NOT NULL, field_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D0A1E46B50A89B2C ON qualification_values (call_id)');
        $this->addSql('CREATE INDEX IDX_D0A1E46B443707B0 ON qualification_values (field_id)');
        $this->addSql('CREATE TABLE users (user_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(50) NOT NULL, prenom VARCHAR(50) NOT NULL, role_users VARCHAR(20) NOT NULL, status VARCHAR(20) DEFAULT \'active\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (user_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON users (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE agent_statuses ADD CONSTRAINT FK_7D2107853414710B FOREIGN KEY (agent_id) REFERENCES users (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call_qualifications ADD CONSTRAINT FK_E1AA67F50A89B2C FOREIGN KEY (call_id) REFERENCES calls (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calls ADD CONSTRAINT FK_DAA35C8FF639F774 FOREIGN KEY (campaign_id) REFERENCES campaigns (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calls ADD CONSTRAINT FK_DAA35C8F3414710B FOREIGN KEY (agent_id) REFERENCES users (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calls ADD CONSTRAINT FK_DAA35C8FE7A1254A FOREIGN KEY (contact_id) REFERENCES contacts (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campaign_fields ADD CONSTRAINT FK_A3A69A25F639F774 FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campaign_users ADD CONSTRAINT FK_5A86C186F639F774 FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campaign_users ADD CONSTRAINT FK_5A86C186A76ED395 FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campaigns ADD CONSTRAINT FK_E373747053C59D72 FOREIGN KEY (responsable_id) REFERENCES users (user_id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contacts ADD CONSTRAINT FK_33401573F639F774 FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE qualification_fields ADD CONSTRAINT FK_94E34B05F639F774 FOREIGN KEY (campaign_id) REFERENCES campaigns (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE qualification_values ADD CONSTRAINT FK_D0A1E46B50A89B2C FOREIGN KEY (call_id) REFERENCES calls (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE qualification_values ADD CONSTRAINT FK_D0A1E46B443707B0 FOREIGN KEY (field_id) REFERENCES qualification_fields (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agent_statuses DROP CONSTRAINT FK_7D2107853414710B');
        $this->addSql('ALTER TABLE call_qualifications DROP CONSTRAINT FK_E1AA67F50A89B2C');
        $this->addSql('ALTER TABLE calls DROP CONSTRAINT FK_DAA35C8FF639F774');
        $this->addSql('ALTER TABLE calls DROP CONSTRAINT FK_DAA35C8F3414710B');
        $this->addSql('ALTER TABLE calls DROP CONSTRAINT FK_DAA35C8FE7A1254A');
        $this->addSql('ALTER TABLE campaign_fields DROP CONSTRAINT FK_A3A69A25F639F774');
        $this->addSql('ALTER TABLE campaign_users DROP CONSTRAINT FK_5A86C186F639F774');
        $this->addSql('ALTER TABLE campaign_users DROP CONSTRAINT FK_5A86C186A76ED395');
        $this->addSql('ALTER TABLE campaigns DROP CONSTRAINT FK_E373747053C59D72');
        $this->addSql('ALTER TABLE contacts DROP CONSTRAINT FK_33401573F639F774');
        $this->addSql('ALTER TABLE qualification_fields DROP CONSTRAINT FK_94E34B05F639F774');
        $this->addSql('ALTER TABLE qualification_values DROP CONSTRAINT FK_D0A1E46B50A89B2C');
        $this->addSql('ALTER TABLE qualification_values DROP CONSTRAINT FK_D0A1E46B443707B0');
        $this->addSql('DROP TABLE agent_statuses');
        $this->addSql('DROP TABLE call_qualifications');
        $this->addSql('DROP TABLE calls');
        $this->addSql('DROP TABLE campaign_fields');
        $this->addSql('DROP TABLE campaign_users');
        $this->addSql('DROP TABLE campaigns');
        $this->addSql('DROP TABLE contacts');
        $this->addSql('DROP TABLE qualification_fields');
        $this->addSql('DROP TABLE qualification_values');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
