<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260211115957 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE call (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duration INT DEFAULT NULL, status VARCHAR(50) NOT NULL, recording_path VARCHAR(255) DEFAULT NULL, qualified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, campaign_id INT NOT NULL, agent_id INT NOT NULL, contact_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CC8E2F3EF639F774 ON call (campaign_id)');
        $this->addSql('CREATE INDEX IDX_CC8E2F3E3414710B ON call (agent_id)');
        $this->addSql('CREATE INDEX IDX_CC8E2F3EE7A1254A ON call (contact_id)');
        $this->addSql('ALTER TABLE call ADD CONSTRAINT FK_CC8E2F3EF639F774 FOREIGN KEY (campaign_id) REFERENCES campaigns (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call ADD CONSTRAINT FK_CC8E2F3E3414710B FOREIGN KEY (agent_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE call ADD CONSTRAINT FK_CC8E2F3EE7A1254A FOREIGN KEY (contact_id) REFERENCES contacts (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE call DROP CONSTRAINT FK_CC8E2F3EF639F774');
        $this->addSql('ALTER TABLE call DROP CONSTRAINT FK_CC8E2F3E3414710B');
        $this->addSql('ALTER TABLE call DROP CONSTRAINT FK_CC8E2F3EE7A1254A');
        $this->addSql('DROP TABLE call');
    }
}
